apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: knote-hpa
  namespace: default
spec:
  maxReplicas: 9
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: knote-ops
  targetCPUUtilizationPercentage: 65
