apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: knote-hpa
  namespace: default
spec:
  maxReplicas: 25
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: knote-ops
  metrics: 
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization 
        averageUtilization: 60 
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 180
